// Autogenerated AST node
package org.python.antlr.ast;

import org.antlr.runtime.Token;
import org.python.antlr.PythonTree;
import org.python.antlr.adapter.AstAdapters;
import org.python.antlr.base.expr;
import org.python.antlr.base.stmt;
import org.python.core.ArgParser;
import org.python.core.Py;
import org.python.core.PyObject;
import org.python.core.PyString;
import org.python.core.PyStringMap;
import org.python.core.PyType;
import org.python.expose.ExposedGet;
import org.python.expose.ExposedMethod;
import org.python.expose.ExposedNew;
import org.python.expose.ExposedSet;
import org.python.expose.ExposedType;

/**
 * Assert
 */
@ExposedType(name = "_ast.Assert", base = stmt.class)
public class Assert extends stmt {
    /** TYPE */
    public static final PyType TYPE = PyType.fromClass(Assert.class);
    private expr test;

    /**
     * GetInternalTest
     * 
     * @return expr
     */
    public expr getInternalTest() {
        return test;
    }

    /**
     * GetTest
     * 
     * @return o
     */
    @ExposedGet(name = "test")
    public PyObject getTest() {
        return test;
    }

    /**
     * setTest
     * 
     * @param test
     *            test
     */
    @ExposedSet(name = "test")
    public void setTest(PyObject test) {
        this.test = AstAdapters.py2expr(test);
    }

    private expr msg;

    /**
     * GetInternalMsg
     * 
     * @return expr
     */
    public expr getInternalMsg() {
        return msg;
    }

    /**
     * GetMsg
     * 
     * @return o
     */
    @ExposedGet(name = "msg")
    public PyObject getMsg() {
        return msg;
    }

    /**
     * SetMsg
     * 
     * @param msg
     *            msg
     */
    @ExposedSet(name = "msg")
    public void setMsg(PyObject msg) {
        this.msg = AstAdapters.py2expr(msg);
    }


    private final static PyString[] fields =
    new PyString[] {new PyString("test"), new PyString("msg")};

    @ExposedGet(name = "_fields")
    public PyString[] get_fields() { return fields; }

    private final static PyString[] attributes =
    new PyString[] {new PyString("lineno"), new PyString("col_offset")};

    @ExposedGet(name = "_attributes")
    public PyString[] get_attributes() { return attributes; }

    /**
     * Constructor
     * 
     * @param subType
     *            subType
     */
    public Assert(PyType subType) {
        super(subType);
    }

    /**
     * Default constructor
     */
    public Assert() {
        this(TYPE);
    }

    /**
     * Assert___init__
     * 
     * @param args
     *            args
     * @param keywords
     *            keywords
     */
    @ExposedNew
    @ExposedMethod
    public void Assert___init__(PyObject[] args, String[] keywords) {
        ArgParser ap = new ArgParser("Assert", args, keywords, new String[]
            {"test", "msg", "lineno", "col_offset"}, 2, true);
        setTest(ap.getPyObject(0, Py.None));
        setMsg(ap.getPyObject(1, Py.None));
        int lin = ap.getInt(2, -1);
        if (lin != -1) {
            setLineno(lin);
        }

        int col = ap.getInt(3, -1);
        if (col != -1) {
            setLineno(col);
        }

    }

    /**
     * Constructor
     * 
     * @param test
     *            test
     * @param msg
     *            msg
     */
    public Assert(PyObject test, PyObject msg) {
        setTest(test);
        setMsg(msg);
    }

    /**
     * Constructor
     * 
     * @param token
     *            token
     * @param test
     *            test
     * @param msg
     *            msg
     */
    public Assert(Token token, expr test, expr msg) {
        super(token);
        this.test = test;
        addChild(test);
        this.msg = msg;
        addChild(msg);
    }

    /**
     * Constructor
     * 
     * @param ttype
     *            ttype
     * @param token
     *            token
     * @param test
     *            test
     * @param msg
     *            msg
     */
    public Assert(Integer ttype, Token token, expr test, expr msg) {
        super(ttype, token);
        this.test = test;
        addChild(test);
        this.msg = msg;
        addChild(msg);
    }

    /**
     * Constructor
     * 
     * @param tree
     *            tree
     * @param test
     *            test
     * @param msg
     *            msg
     */
    public Assert(PythonTree tree, expr test, expr msg) {
        super(tree);
        this.test = test;
        addChild(test);
        this.msg = msg;
        addChild(msg);
    }

    @ExposedGet(name = "repr")
    public String toString() {
        return "Assert";
    }

    public String toStringTree() {
        StringBuffer sb = new StringBuffer("Assert(");
        sb.append("test=");
        sb.append(dumpThis(test));
        sb.append(",");
        sb.append("msg=");
        sb.append(dumpThis(msg));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitAssert(this);
    }

    public void traverse(VisitorIF<?> visitor) throws Exception {
        if (test != null)
            test.accept(visitor);
        if (msg != null)
            msg.accept(visitor);
    }

    /** __dict__ */
    public PyObject __dict__;

    @Override
    public PyObject fastGetDict() {
        ensureDict();
        return __dict__;
    }

    @ExposedGet(name = "__dict__")
    public PyObject getDict() {
        return fastGetDict();
    }

    private void ensureDict() {
        if (__dict__ == null) {
            __dict__ = new PyStringMap();
        }
    }

    private int lineno = -1;
    @ExposedGet(name = "lineno")
    public int getLineno() {
        if (lineno != -1) {
            return lineno;
        }
        return getLine();
    }

    /**
     * SetLineno
     * 
     * @param num
     *            num
     */
    @ExposedSet(name = "lineno")
    public void setLineno(int num) {
        lineno = num;
    }

    private int col_offset = -1;
    @ExposedGet(name = "col_offset")
    public int getCol_offset() {
        if (col_offset != -1) {
            return col_offset;
        }
        return getCharPositionInLine();
    }

    /**
     * SetCol_offset
     * 
     * @param num
     *            num
     */
    @ExposedSet(name = "col_offset")
    public void setCol_offset(int num) {
        col_offset = num;
    }

}
