// Autogenerated AST node
package org.python.antlr.ast;

import java.util.ArrayList;

import org.antlr.runtime.Token;
import org.python.antlr.PythonTree;
import org.python.antlr.adapter.AstAdapters;
import org.python.antlr.base.expr;
import org.python.antlr.base.stmt;
import org.python.core.ArgParser;
import org.python.core.AstList;
import org.python.core.Py;
import org.python.core.PyObject;
import org.python.core.PyString;
import org.python.core.PyStringMap;
import org.python.core.PyType;
import org.python.expose.ExposedGet;
import org.python.expose.ExposedMethod;
import org.python.expose.ExposedNew;
import org.python.expose.ExposedSet;
import org.python.expose.ExposedType;

/**
 * Assign
 */
@ExposedType(name = "_ast.Assign", base = stmt.class)
public class Assign extends stmt {
    /** TYPE */
    public static final PyType TYPE = PyType.fromClass(Assign.class);
    private java.util.List<expr> targets;

    /**
     * GetInternalTargets
     * 
     * @return list
     */
    public java.util.List<expr> getInternalTargets() {
        return targets;
    }

    /**
     * GetTargets
     * 
     * @return o
     */
    @ExposedGet(name = "targets")
    public PyObject getTargets() {
        return new AstList(targets, AstAdapters.exprAdapter);
    }

    /**
     * SetTargets
     * 
     * @param targets
     *            targets
     */
    @ExposedSet(name = "targets")
    public void setTargets(PyObject targets) {
        this.targets = AstAdapters.py2exprList(targets);
    }

    private expr value;

    /**
     * GetInternalValue
     * 
     * @return expr
     */
    public expr getInternalValue() {
        return value;
    }

    /**
     * GetValue
     * 
     * @return o
     */
    @ExposedGet(name = "value")
    public PyObject getValue() {
        return value;
    }

    /**
     * SetValue
     * 
     * @param value
     *            value
     */
    @ExposedSet(name = "value")
    public void setValue(PyObject value) {
        this.value = AstAdapters.py2expr(value);
    }


    private final static PyString[] fields =
    new PyString[] {new PyString("targets"), new PyString("value")};
    @ExposedGet(name = "_fields")
    public PyString[] get_fields() { return fields; }

    private final static PyString[] attributes =
    new PyString[] {new PyString("lineno"), new PyString("col_offset")};
    @ExposedGet(name = "_attributes")
    public PyString[] get_attributes() { return attributes; }

    /**
     * Constructor
     * 
     * @param subType
     *            subTupe
     */
    public Assign(PyType subType) {
        super(subType);
    }

    /**
     * Default constructor
     */
    public Assign() {
        this(TYPE);
    }

    /**
     * Assign___init__
     * 
     * @param args
     *            args
     * @param keywords
     *            keywords
     */
    @ExposedNew
    @ExposedMethod
    public void Assign___init__(PyObject[] args, String[] keywords) {
        ArgParser ap = new ArgParser("Assign", args, keywords, new String[]
            {"targets", "value", "lineno", "col_offset"}, 2, true);
        setTargets(ap.getPyObject(0, Py.None));
        setValue(ap.getPyObject(1, Py.None));
        int lin = ap.getInt(2, -1);
        if (lin != -1) {
            setLineno(lin);
        }

        int col = ap.getInt(3, -1);
        if (col != -1) {
            setLineno(col);
        }

    }

    /**
     * Constructor
     * 
     * @param targets
     *            targets
     * @param value
     *            value
     */
    public Assign(PyObject targets, PyObject value) {
        setTargets(targets);
        setValue(value);
    }

    /**
     * Constructor
     * 
     * @param token
     *            token
     * @param targets
     *            targets
     * @param value
     *            value
     */
    public Assign(Token token, java.util.List<expr> targets, expr value) {
        super(token);
        this.targets = targets;
        if (targets == null) {
            this.targets = new ArrayList<expr>();
        }
        for(PythonTree t : this.targets) {
            addChild(t);
        }
        this.value = value;
        addChild(value);
    }

    /**
     * Constructor
     * 
     * @param ttype
     *            ttype
     * @param token
     *            token
     * @param targets
     *            targets
     * @param value
     *            value
     */
    public Assign(Integer ttype, Token token, java.util.List<expr> targets, expr value) {
        super(ttype, token);
        this.targets = targets;
        if (targets == null) {
            this.targets = new ArrayList<expr>();
        }
        for(PythonTree t : this.targets) {
            addChild(t);
        }
        this.value = value;
        addChild(value);
    }

    /**
     * Constructor
     * 
     * @param tree
     *            tree
     * @param targets
     *            targets
     * @param value
     *            value
     */
    public Assign(PythonTree tree, java.util.List<expr> targets, expr value) {
        super(tree);
        this.targets = targets;
        if (targets == null) {
            this.targets = new ArrayList<expr>();
        }
        for(PythonTree t : this.targets) {
            addChild(t);
        }
        this.value = value;
        addChild(value);
    }

    @ExposedGet(name = "repr")
    public String toString() {
        return "Assign";
    }

    public String toStringTree() {
        StringBuffer sb = new StringBuffer("Assign(");
        sb.append("targets=");
        sb.append(dumpThis(targets));
        sb.append(",");
        sb.append("value=");
        sb.append(dumpThis(value));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitAssign(this);
    }

    public void traverse(VisitorIF<?> visitor) throws Exception {
        if (targets != null) {
            for (PythonTree t : targets) {
                if (t != null)
                    t.accept(visitor);
            }
        }
        if (value != null)
            value.accept(visitor);
    }

    /** __dict__ */
    public PyObject __dict__;

    @Override
    public PyObject fastGetDict() {
        ensureDict();
        return __dict__;
    }

    @ExposedGet(name = "__dict__")
    public PyObject getDict() {
        return fastGetDict();
    }

    private void ensureDict() {
        if (__dict__ == null) {
            __dict__ = new PyStringMap();
        }
    }

    private int lineno = -1;
    @ExposedGet(name = "lineno")
    public int getLineno() {
        if (lineno != -1) {
            return lineno;
        }
        return getLine();
    }

    /**
     * SetLineno
     * 
     * @param num
     *            num
     */
    @ExposedSet(name = "lineno")
    public void setLineno(int num) {
        lineno = num;
    }

    private int col_offset = -1;
    @ExposedGet(name = "col_offset")
    public int getCol_offset() {
        if (col_offset != -1) {
            return col_offset;
        }
        return getCharPositionInLine();
    }

    /**
     * SetCol_offset
     * 
     * @param num
     *            num
     */
    @ExposedSet(name = "col_offset")
    public void setCol_offset(int num) {
        col_offset = num;
    }

}
