// Autogenerated AST node
package org.python.antlr.ast;

import java.util.ArrayList;

import org.antlr.runtime.Token;
import org.python.antlr.PythonTree;
import org.python.antlr.adapter.AstAdapters;
import org.python.antlr.base.expr;
import org.python.core.ArgParser;
import org.python.core.AstList;
import org.python.core.Py;
import org.python.core.PyObject;
import org.python.core.PyString;
import org.python.core.PyStringMap;
import org.python.core.PyType;
import org.python.expose.ExposedGet;
import org.python.expose.ExposedMethod;
import org.python.expose.ExposedNew;
import org.python.expose.ExposedSet;
import org.python.expose.ExposedType;

/**
 * BoolOp
 */
@ExposedType(name = "_ast.BoolOp", base = expr.class)
public class BoolOp extends expr {
    /** TYPE */
    public static final PyType TYPE = PyType.fromClass(BoolOp.class);
    private boolopType op;

    /**
     * GetInternalOp
     * 
     * @return type
     */
    public boolopType getInternalOp() {
        return op;
    }

    /**
     * GetOp
     * 
     * @return o
     */
    @ExposedGet(name = "op")
    public PyObject getOp() {
        return AstAdapters.boolop2py(op);
    }

    /**
     * SetOp
     * 
     * @param op
     *            op
     */
    @ExposedSet(name = "op")
    public void setOp(PyObject op) {
        this.op = AstAdapters.py2boolop(op);
    }

    private java.util.List<expr> values;

    /**
     * GetInternalValues
     * 
     * @return list
     */
    public java.util.List<expr> getInternalValues() {
        return values;
    }

    /**
     * GetValues
     * 
     * @return o
     */
    @ExposedGet(name = "values")
    public PyObject getValues() {
        return new AstList(values, AstAdapters.exprAdapter);
    }

    /**
     * SetValues
     * 
     * @param values
     *            values
     */
    @ExposedSet(name = "values")
    public void setValues(PyObject values) {
        this.values = AstAdapters.py2exprList(values);
    }


    private final static PyString[] fields =
    new PyString[] {new PyString("op"), new PyString("values")};

    /**
     * Get_fields
     * 
     * @return fields
     */
    @ExposedGet(name = "_fields")
    public PyString[] get_fields() { return fields; }

    private final static PyString[] attributes =
    new PyString[] {new PyString("lineno"), new PyString("col_offset")};

    /**
     * Get_attributes
     * 
     * @return attributes
     */
    @ExposedGet(name = "_attributes")
    public PyString[] get_attributes() { return attributes; }

    /**
     * Constructor
     * 
     * @param subType
     *            subType
     */
    public BoolOp(PyType subType) {
        super(subType);
    }

    /** Default constructor */
    public BoolOp() {
        this(TYPE);
    }

    /**
     * BoolOp___init__
     * 
     * @param args
     *            args
     * @param keywords
     *            keywords
     */
    @ExposedNew
    @ExposedMethod
    public void BoolOp___init__(PyObject[] args, String[] keywords) {
        ArgParser ap = new ArgParser("BoolOp", args, keywords, new String[]
            {"op", "values", "lineno", "col_offset"}, 2, true);
        setOp(ap.getPyObject(0, Py.None));
        setValues(ap.getPyObject(1, Py.None));
        int lin = ap.getInt(2, -1);
        if (lin != -1) {
            setLineno(lin);
        }

        int col = ap.getInt(3, -1);
        if (col != -1) {
            setLineno(col);
        }

    }

    /**
     * Constructor
     * 
     * @param op
     *            op
     * @param values
     *            values
     */
    public BoolOp(PyObject op, PyObject values) {
        setOp(op);
        setValues(values);
    }

    /**
     * Constructor
     * 
     * @param token
     *            token
     * @param op
     *            op
     * @param values
     *            values
     */
    public BoolOp(Token token, boolopType op, java.util.List<expr> values) {
        super(token);
        this.op = op;
        this.values = values;
        if (values == null) {
            this.values = new ArrayList<expr>();
        }
        for(PythonTree t : this.values) {
            addChild(t);
        }
    }

    /**
     * Constructor
     * 
     * @param ttype
     *            ttype
     * @param token
     *            token
     * @param op
     *            op
     * @param values
     *            values
     */
    public BoolOp(Integer ttype, Token token, boolopType op, java.util.List<expr> values) {
        super(ttype, token);
        this.op = op;
        this.values = values;
        if (values == null) {
            this.values = new ArrayList<expr>();
        }
        for(PythonTree t : this.values) {
            addChild(t);
        }
    }

    /**
     * Constructor
     * 
     * @param tree
     *            tree
     * @param op
     *            op
     * @param values
     *            values
     */
    public BoolOp(PythonTree tree, boolopType op, java.util.List<expr> values) {
        super(tree);
        this.op = op;
        this.values = values;
        if (values == null) {
            this.values = new ArrayList<expr>();
        }
        for(PythonTree t : this.values) {
            addChild(t);
        }
    }

    @ExposedGet(name = "repr")
    public String toString() {
        return "BoolOp";
    }

    public String toStringTree() {
        StringBuffer sb = new StringBuffer("BoolOp(");
        sb.append("op=");
        sb.append(dumpThis(op));
        sb.append(",");
        sb.append("values=");
        sb.append(dumpThis(values));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitBoolOp(this);
    }

    public void traverse(VisitorIF<?> visitor) throws Exception {
        if (values != null) {
            for (PythonTree t : values) {
                if (t != null)
                    t.accept(visitor);
            }
        }
    }

    /** __dict__ */
    public PyObject __dict__;

    @Override
    public PyObject fastGetDict() {
        ensureDict();
        return __dict__;
    }

    @ExposedGet(name = "__dict__")
    public PyObject getDict() {
        return fastGetDict();
    }

    private void ensureDict() {
        if (__dict__ == null) {
            __dict__ = new PyStringMap();
        }
    }

    private int lineno = -1;
    @ExposedGet(name = "lineno")
    public int getLineno() {
        if (lineno != -1) {
            return lineno;
        }
        return getLine();
    }

    /**
     * SetLineno
     * 
     * @param num
     *            num
     */
    @ExposedSet(name = "lineno")
    public void setLineno(int num) {
        lineno = num;
    }

    private int col_offset = -1;
    @ExposedGet(name = "col_offset")
    public int getCol_offset() {
        if (col_offset != -1) {
            return col_offset;
        }
        return getCharPositionInLine();
    }

    /**
     * SetCol_offset
     * 
     * @param num
     *            num
     */
    @ExposedSet(name = "col_offset")
    public void setCol_offset(int num) {
        col_offset = num;
    }

}
