// Autogenerated AST node
package org.python.antlr.ast;

/**
 * cmpopType
 */
public enum cmpopType {
    /** UNDEFINED */
    UNDEFINED,
    /** Eq */
    Eq,
    /** NotEq */
    NotEq,
    /** Lt */
    Lt,
    /** LtE */
    LtE,
    /** Gt */
    Gt,
    /** GtE */
    GtE,
    /** Is */
    Is,
    /** IsNot */
    IsNot,
    /** In */
    In,
    /** NotIn */
    NotIn;
}
