// Autogenerated AST node
package org.python.antlr.ast;

import java.util.ArrayList;

import org.antlr.runtime.Token;
import org.python.antlr.PythonTree;
import org.python.antlr.adapter.AstAdapters;
import org.python.antlr.base.expr;
import org.python.core.ArgParser;
import org.python.core.AstList;
import org.python.core.Py;
import org.python.core.PyObject;
import org.python.core.PyString;
import org.python.core.PyStringMap;
import org.python.core.PyType;
import org.python.expose.ExposedGet;
import org.python.expose.ExposedMethod;
import org.python.expose.ExposedNew;
import org.python.expose.ExposedSet;
import org.python.expose.ExposedType;

/**
 * Compare
 */
@ExposedType(name = "_ast.Compare", base = expr.class)
public class Compare extends expr {
    /** TYPE */
    public static final PyType TYPE = PyType.fromClass(Compare.class);

    private expr left;

    /**
     * GetInternalLeft
     * 
     * @return expr
     */
    public expr getInternalLeft() {
        return left;
    }

    /**
     * GetLeft
     * 
     * @return o
     */
    @ExposedGet(name = "left")
    public PyObject getLeft() {
        return left;
    }

    /**
     * SetLeft
     * 
     * @param left
     *            lef
     */
    @ExposedSet(name = "left")
    public void setLeft(PyObject left) {
        this.left = AstAdapters.py2expr(left);
    }

    private java.util.List<cmpopType> ops;

    /**
     * GetInternalOps
     * 
     * @return list
     */
    public java.util.List<cmpopType> getInternalOps() {
        return ops;
    }

    /**
     * GetOps
     * 
     * @return o
     */
    @ExposedGet(name = "ops")
    public PyObject getOps() {
        return new AstList(ops, AstAdapters.cmpopAdapter);
    }

    /**
     * SetOops
     * 
     * @param ops
     *            ops
     */
    @ExposedSet(name = "ops")
    public void setOps(PyObject ops) {
        this.ops = AstAdapters.py2cmpopList(ops);
    }

    private java.util.List<expr> comparators;

    /**
     * GetInternalComparators
     * 
     * @return list
     */
    public java.util.List<expr> getInternalComparators() {
        return comparators;
    }

    /**
     * GetComparators
     * 
     * @return o
     */
    @ExposedGet(name = "comparators")
    public PyObject getComparators() {
        return new AstList(comparators, AstAdapters.exprAdapter);
    }

    /**
     * SetComparators
     * 
     * @param comparators
     *            comparators
     */
    @ExposedSet(name = "comparators")
    public void setComparators(PyObject comparators) {
        this.comparators = AstAdapters.py2exprList(comparators);
    }


    private final static PyString[] fields =
    new PyString[] {new PyString("left"), new PyString("ops"), new PyString("comparators")};

    /**
     * Get_fields
     * 
     * @return fields
     */
    @ExposedGet(name = "_fields")
    public PyString[] get_fields() { return fields; }

    private final static PyString[] attributes =
    new PyString[] {new PyString("lineno"), new PyString("col_offset")};

    /**
     * Get_attributes
     * 
     * @return attributes
     */
    @ExposedGet(name = "_attributes")
    public PyString[] get_attributes() { return attributes; }

    /**
     * Constructor
     * 
     * @param subType
     *            subType
     */
    public Compare(PyType subType) {
        super(subType);
    }

    /** Default constructor */
    public Compare() {
        this(TYPE);
    }

    /**
     * Compare___init__
     * 
     * @param args
     *            args
     * @param keywords
     *            keywords
     */
    @ExposedNew
    @ExposedMethod
    public void Compare___init__(PyObject[] args, String[] keywords) {
        ArgParser ap = new ArgParser("Compare", args, keywords, new String[]
            {"left", "ops", "comparators", "lineno", "col_offset"}, 3, true);
        setLeft(ap.getPyObject(0, Py.None));
        setOps(ap.getPyObject(1, Py.None));
        setComparators(ap.getPyObject(2, Py.None));
        int lin = ap.getInt(3, -1);
        if (lin != -1) {
            setLineno(lin);
        }

        int col = ap.getInt(4, -1);
        if (col != -1) {
            setLineno(col);
        }

    }

    /**
     * Constructor
     * 
     * @param left
     *            left
     * @param ops
     *            ops
     * @param comparators
     *            comparators
     */
    public Compare(PyObject left, PyObject ops, PyObject comparators) {
        setLeft(left);
        setOps(ops);
        setComparators(comparators);
    }

    /**
     * Constructor
     * 
     * @param token
     *            token
     * @param left
     *            left
     * @param ops
     *            ops
     * @param comparators
     *            comparators
     */
    public Compare(Token token, expr left, java.util.List<cmpopType> ops, java.util.List<expr> comparators) {
        super(token);
        this.left = left;
        addChild(left);
        this.ops = ops;
        this.comparators = comparators;
        if (comparators == null) {
            this.comparators = new ArrayList<expr>();
        }
        for(PythonTree t : this.comparators) {
            addChild(t);
        }
    }

    /**
     * Constructor
     * 
     * @param ttype
     *            ttype
     * @param token
     *            token
     * @param left
     *            left
     * @param ops
     *            ops
     * @param comparators
     *            comparators
     */
    public Compare(Integer ttype, Token token, expr left, java.util.List<cmpopType> ops,
    java.util.List<expr> comparators) {
        super(ttype, token);
        this.left = left;
        addChild(left);
        this.ops = ops;
        this.comparators = comparators;
        if (comparators == null) {
            this.comparators = new ArrayList<expr>();
        }
        for(PythonTree t : this.comparators) {
            addChild(t);
        }
    }

    /**
     * Constructor
     * 
     * @param tree
     *            tree
     * @param left
     *            left
     * @param ops
     *            ops
     * @param comparators
     *            comparators
     */
    public Compare(PythonTree tree, expr left, java.util.List<cmpopType> ops, java.util.List<expr>
    comparators) {
        super(tree);
        this.left = left;
        addChild(left);
        this.ops = ops;
        this.comparators = comparators;
        if (comparators == null) {
            this.comparators = new ArrayList<expr>();
        }
        for(PythonTree t : this.comparators) {
            addChild(t);
        }
    }

    @ExposedGet(name = "repr")
    public String toString() {
        return "Compare";
    }

    public String toStringTree() {
        StringBuffer sb = new StringBuffer("Compare(");
        sb.append("left=");
        sb.append(dumpThis(left));
        sb.append(",");
        sb.append("ops=");
        sb.append(dumpThis(ops));
        sb.append(",");
        sb.append("comparators=");
        sb.append(dumpThis(comparators));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        return visitor.visitCompare(this);
    }

    public void traverse(VisitorIF<?> visitor) throws Exception {
        if (left != null)
            left.accept(visitor);
        if (comparators != null) {
            for (PythonTree t : comparators) {
                if (t != null)
                    t.accept(visitor);
            }
        }
    }

    /** __dict__ */
    public PyObject __dict__;

    @Override
    public PyObject fastGetDict() {
        ensureDict();
        return __dict__;
    }

    /**
     * GetDict
     * 
     * @return o
     */
    @ExposedGet(name = "__dict__")
    public PyObject getDict() {
        return fastGetDict();
    }

    private void ensureDict() {
        if (__dict__ == null) {
            __dict__ = new PyStringMap();
        }
    }

    private int lineno = -1;

    /**
     * GetLineno
     * 
     * @return i
     */
    @ExposedGet(name = "lineno")
    public int getLineno() {
        if (lineno != -1) {
            return lineno;
        }
        return getLine();
    }

    /**
     * SetLineno
     * 
     * @param num
     *            num
     */
    @ExposedSet(name = "lineno")
    public void setLineno(int num) {
        lineno = num;
    }

    private int col_offset = -1;

    /**
     * GetCol_offset
     * 
     * @return i
     */
    @ExposedGet(name = "col_offset")
    public int getCol_offset() {
        if (col_offset != -1) {
            return col_offset;
        }
        return getCharPositionInLine();
    }

    /**
     * SetCol_offset
     * 
     * @param num
     *            num
     */
    @ExposedSet(name = "col_offset")
    public void setCol_offset(int num) {
        col_offset = num;
    }

}
