// Autogenerated AST node
package org.python.antlr.ast;

/**
 * VisitorIF
 * 
 * @param <R>
 *            R
 */
public interface VisitorIF<R> {

    /**
     * VisitModule
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitModule(Module node) throws Exception;

    /**
     * VisitInteractive
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitInteractive(Interactive node) throws Exception;

    /**
     * VisitExpression
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitExpression(Expression node) throws Exception;

    /**
     * VisitSuite
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitSuite(Suite node) throws Exception;

    /**
     * VisitFunctionDef
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitFunctionDef(FunctionDef node) throws Exception;

    /**
     * VisitClassDef
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitClassDef(ClassDef node) throws Exception;

    /**
     * VisitReturn
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitReturn(Return node) throws Exception;

    /**
     * VisitDelete
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitDelete(Delete node) throws Exception;

    /**
     * VisitAssign
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitAssign(Assign node) throws Exception;

    /**
     * VisitAugAssign
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitAugAssign(AugAssign node) throws Exception;

    /**
     * VisitPrint
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitPrint(Print node) throws Exception;

    /**
     * VisitFor
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitFor(For node) throws Exception;

    /**
     * VisitWhile
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitWhile(While node) throws Exception;

    /**
     * VisitIf
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitIf(If node) throws Exception;

    /**
     * VisitWith
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitWith(With node) throws Exception;

    /**
     * VisitRaise
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitRaise(Raise node) throws Exception;

    /**
     * VisitTryExcept
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitTryExcept(TryExcept node) throws Exception;

    /**
     * VisitTryFinally
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitTryFinally(TryFinally node) throws Exception;

    /**
     * VisitAssert
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitAssert(Assert node) throws Exception;

    /**
     * VisitImport
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitImport(Import node) throws Exception;

    /**
     * VisitImportFrom
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitImportFrom(ImportFrom node) throws Exception;

    /**
     * VisitExec
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitExec(Exec node) throws Exception;

    /**
     * VisitGlobal
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitGlobal(Global node) throws Exception;

    /**
     * VisitExpr
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitExpr(Expr node) throws Exception;

    /**
     * VisitPass
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitPass(Pass node) throws Exception;

    /**
     * VisitBreak
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitBreak(Break node) throws Exception;

    /**
     * VisitContinue
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitContinue(Continue node) throws Exception;

    /**
     * VisitBoolOp
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitBoolOp(BoolOp node) throws Exception;

    /**
     * VisitBinOp
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitBinOp(BinOp node) throws Exception;

    /**
     * VisitUnaryOp
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitUnaryOp(UnaryOp node) throws Exception;

    /**
     * VisitLambda
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitLambda(Lambda node) throws Exception;

    /**
     * VisitIfExp
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitIfExp(IfExp node) throws Exception;

    /**
     * VisitDict
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitDict(Dict node) throws Exception;

    /**
     * VisitSet
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitSet(Set node) throws Exception;

    /**
     * VisitListComp
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitListComp(ListComp node) throws Exception;

    /**
     * VisitSetComp
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitSetComp(SetComp node) throws Exception;

    /**
     * VisitDictComp
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitDictComp(DictComp node) throws Exception;

    /**
     * VisitGeneratorExp
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitGeneratorExp(GeneratorExp node) throws Exception;

    /**
     * VisitYield
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitYield(Yield node) throws Exception;

    /**
     * VisitCompare
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitCompare(Compare node) throws Exception;

    /**
     * VisitCall
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitCall(Call node) throws Exception;

    /**
     * VisitRepr
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitRepr(Repr node) throws Exception;

    /**
     * VisitNum
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitNum(Num node) throws Exception;

    /**
     * VisitStr
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitStr(Str node) throws Exception;

    /**
     * VisitAttribute
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitAttribute(Attribute node) throws Exception;

    /**
     * VisitSubscript
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitSubscript(Subscript node) throws Exception;

    /**
     * VisitName
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitName(Name node) throws Exception;

    /**
     * VisitList
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitList(List node) throws Exception;

    /**
     * VisitTuple
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitTuple(Tuple node) throws Exception;

    /**
     * VisitEllipsis
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitEllipsis(Ellipsis node) throws Exception;

    /**
     * VisitSlice
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitSlice(Slice node) throws Exception;

    /**
     * VisitExtSlice
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitExtSlice(ExtSlice node) throws Exception;

    /**
     * VisitIndex
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitIndex(Index node) throws Exception;

    /**
     * VisitExceptHandler
     * 
     * @param node
     *            node
     * @return R
     * @throws Exception
     *             exception
     */
    public R visitExceptHandler(ExceptHandler node) throws Exception;
}
