// Autogenerated AST node
package org.python.antlr.op;

import org.python.antlr.PythonTree;
import org.python.antlr.base.operator;
import org.python.core.Py;
import org.python.core.PyObject;
import org.python.core.PyString;
import org.python.core.PyType;
import org.python.expose.ExposedGet;
import org.python.expose.ExposedMethod;
import org.python.expose.ExposedNew;
import org.python.expose.ExposedType;

/**
 * BitOr
 */
@ExposedType(name = "_ast.BitOr", base = operator.class)
public class BitOr extends PythonTree {
    /** TYPE */
    public static final PyType TYPE = PyType.fromClass(BitOr.class);

    /** Default constructpr */
    public BitOr() {
    }

    /**
     * Constructor
     * 
     * @param subType
     *            subType
     */
    public BitOr(PyType subType) {
        super(subType);
    }

    /**
     * BitOr___init__
     * 
     * @param args
     *            args
     * @param keywords
     *            keywords
     */
    @ExposedNew
    @ExposedMethod
    public void BitOr___init__(PyObject[] args, String[] keywords) {
    }

    private final static PyString[] fields = new PyString[0];

    /**
     * Get_fields
     * 
     * @return fields
     */
    @ExposedGet(name = "_fields")
    public PyString[] get_fields() { return fields; }

    private final static PyString[] attributes = new PyString[0];

    /**
     * Get_attributes
     * 
     * @return attributes
     */
    @ExposedGet(name = "_attributes")
    public PyString[] get_attributes() { return attributes; }

    /**
     * __int__
     * 
     * @return o
     */
    @ExposedMethod
    public PyObject __int__() {
        return BitOr___int__();
    }

    final PyObject BitOr___int__() {
        return Py.newInteger(9);
    }

}
